//! Public mirror types for Assetto Corsa shared-memory structs.
//!
//! These are safe, non-packed copies of the raw `SPageFile*` structs.
//! `[u16; N]` string fields are wrapped in [`SimStringU16<N>`] and
//! `[u8; N]` string fields are wrapped in [`SimString<N>`].

use crate::ac::structs::{
    SMEvoTyreState, SPageFileGraphics, SPageFileGraphicsEvo, SPageFilePhysics, SPageFilePhysicsEvo,
    SPageFileStatic, SPageFileStaticEvo,
};
use crate::sim_string::SimStringU16;

// ── Classic AC ────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct AcPhysicsData {
    pub packet_id: i32,
    pub gas: f32,
    pub brake: f32,
    pub fuel: f32,
    pub gear: i32,
    pub rpms: i32,
    pub steer_angle: f32,
    pub speed_kmh: f32,
    pub velocity: [f32; 3],
    pub acc_g: [f32; 3],
    pub wheel_slip: [f32; 4],
    pub wheel_load: [f32; 4],
    pub wheels_pressure: [f32; 4],
    pub wheel_angular_speed: [f32; 4],
    pub tyre_wear: [f32; 4],
    pub tyre_dirty_level: [f32; 4],
    pub tyre_core_temperature: [f32; 4],
    pub camber_rad: [f32; 4],
    pub suspension_travel: [f32; 4],
    pub drs: f32,
    pub tc: f32,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub cg_height: f32,
    pub car_damage: [f32; 5],
    pub number_of_tyres_out: i32,
    pub pit_limiter_on: i32,
    pub abs: f32,
    pub kers_charge: f32,
    pub kers_input: f32,
    pub auto_shifter_on: i32,
    pub ride_height: [f32; 2],
    pub turbo_boost: f32,
    pub ballast: f32,
    pub air_density: f32,
    pub air_temp: f32,
    pub road_temp: f32,
    pub local_angular_vel: [f32; 3],
    pub final_ff: f32,
    pub performance_meter: f32,
    pub engine_brake: i32,
    pub ers_recovery_level: i32,
    pub ers_power_level: i32,
    pub ers_heat_charging: i32,
    pub ers_is_charging: i32,
    pub kers_current_kj: f32,
    pub drs_available: i32,
    pub drs_enabled: i32,
    pub brake_temp: [f32; 4],
    pub clutch: f32,
    pub tyre_temp_i: [f32; 4],
    pub tyre_temp_m: [f32; 4],
    pub tyre_temp_o: [f32; 4],
    pub is_ai_controlled: i32,
    pub tyre_contact_point: [[f32; 3]; 4],
    pub tyre_contact_normal: [[f32; 3]; 4],
    pub tyre_contact_heading: [[f32; 3]; 4],
    pub brake_bias: f32,
    pub local_velocity: [f32; 3],
}

impl From<SPageFilePhysics> for AcPhysicsData {
    fn from(raw: SPageFilePhysics) -> Self {
        Self {
            packet_id: raw.packet_id,
            gas: raw.gas,
            brake: raw.brake,
            fuel: raw.fuel,
            gear: raw.gear,
            rpms: raw.rpms,
            steer_angle: raw.steer_angle,
            speed_kmh: raw.speed_kmh,
            velocity: raw.velocity,
            acc_g: raw.acc_g,
            wheel_slip: raw.wheel_slip,
            wheel_load: raw.wheel_load,
            wheels_pressure: raw.wheels_pressure,
            wheel_angular_speed: raw.wheel_angular_speed,
            tyre_wear: raw.tyre_wear,
            tyre_dirty_level: raw.tyre_dirty_level,
            tyre_core_temperature: raw.tyre_core_temperature,
            camber_rad: raw.camber_rad,
            suspension_travel: raw.suspension_travel,
            drs: raw.drs,
            tc: raw.tc,
            heading: raw.heading,
            pitch: raw.pitch,
            roll: raw.roll,
            cg_height: raw.cg_height,
            car_damage: raw.car_damage,
            number_of_tyres_out: raw.number_of_tyres_out,
            pit_limiter_on: raw.pit_limiter_on,
            abs: raw.abs,
            kers_charge: raw.kers_charge,
            kers_input: raw.kers_input,
            auto_shifter_on: raw.auto_shifter_on,
            ride_height: raw.ride_height,
            turbo_boost: raw.turbo_boost,
            ballast: raw.ballast,
            air_density: raw.air_density,
            air_temp: raw.air_temp,
            road_temp: raw.road_temp,
            local_angular_vel: raw.local_angular_vel,
            final_ff: raw.final_ff,
            performance_meter: raw.performance_meter,
            engine_brake: raw.engine_brake,
            ers_recovery_level: raw.ers_recovery_level,
            ers_power_level: raw.ers_power_level,
            ers_heat_charging: raw.ers_heat_charging,
            ers_is_charging: raw.ers_is_charging,
            kers_current_kj: raw.kers_current_kj,
            drs_available: raw.drs_available,
            drs_enabled: raw.drs_enabled,
            brake_temp: raw.brake_temp,
            clutch: raw.clutch,
            tyre_temp_i: raw.tyre_temp_i,
            tyre_temp_m: raw.tyre_temp_m,
            tyre_temp_o: raw.tyre_temp_o,
            is_ai_controlled: raw.is_ai_controlled,
            tyre_contact_point: raw.tyre_contact_point,
            tyre_contact_normal: raw.tyre_contact_normal,
            tyre_contact_heading: raw.tyre_contact_heading,
            brake_bias: raw.brake_bias,
            local_velocity: raw.local_velocity,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct AcGraphicsData {
    pub packet_id: i32,
    pub status: i32,
    pub session: i32,
    pub current_time: SimStringU16<15>,
    pub last_time: SimStringU16<15>,
    pub best_time: SimStringU16<15>,
    pub split: SimStringU16<15>,
    pub completed_laps: i32,
    pub position: i32,
    pub i_current_time: i32,
    pub i_last_time: i32,
    pub i_best_time: i32,
    pub session_time_left: f32,
    pub distance_traveled: f32,
    pub is_in_pit: i32,
    pub current_sector_index: i32,
    pub last_sector_time: i32,
    pub number_of_laps: i32,
    pub tyre_compound: SimStringU16<33>,
    pub replay_time_multiplier: f32,
    pub normalized_car_position: f32,
    pub active_cars: i32,
    #[serde(skip)]
    pub car_coordinates: [[f32; 3]; 60],
    #[serde(skip)]
    pub car_id: [i32; 60],
    pub player_car_id: i32,
    pub penalty_time: f32,
    pub flag: i32,
    pub penalty: i32,
    pub ideal_line_on: i32,
    pub is_in_pit_lane: i32,
    pub surface_grip: f32,
    pub mandatory_pit_done: i32,
    pub wind_speed: f32,
    pub wind_direction: f32,
    pub is_setup_menu_visible: i32,
    pub main_display_index: i32,
    pub secondary_display_index: i32,
    pub tc: i32,
    pub tc_cut: i32,
    pub engine_map: i32,
    pub abs: i32,
    pub fuel_xlap: f32,
    pub rain_lights: i32,
    pub flashing_lights: i32,
    pub lights_stage: i32,
    pub exhaust_temperature: f32,
    pub wiper_lv: i32,
    pub driver_stint_total_time_left: i32,
    pub driver_stint_time_left: i32,
    pub rain_tyres: i32,
}

impl From<SPageFileGraphics> for AcGraphicsData {
    fn from(raw: SPageFileGraphics) -> Self {
        Self {
            packet_id: raw.packet_id,
            status: raw.status,
            session: raw.session,
            current_time: SimStringU16::from_u16_array(raw.current_time),
            last_time: SimStringU16::from_u16_array(raw.last_time),
            best_time: SimStringU16::from_u16_array(raw.best_time),
            split: SimStringU16::from_u16_array(raw.split),
            completed_laps: raw.completed_laps,
            position: raw.position,
            i_current_time: raw.i_current_time,
            i_last_time: raw.i_last_time,
            i_best_time: raw.i_best_time,
            session_time_left: raw.session_time_left,
            distance_traveled: raw.distance_traveled,
            is_in_pit: raw.is_in_pit,
            current_sector_index: raw.current_sector_index,
            last_sector_time: raw.last_sector_time,
            number_of_laps: raw.number_of_laps,
            tyre_compound: SimStringU16::from_u16_array(raw.tyre_compound),
            replay_time_multiplier: raw.replay_time_multiplier,
            normalized_car_position: raw.normalized_car_position,
            active_cars: raw.active_cars,
            car_coordinates: raw.car_coordinates,
            car_id: raw.car_id,
            player_car_id: raw.player_car_id,
            penalty_time: raw.penalty_time,
            flag: raw.flag,
            penalty: raw.penalty,
            ideal_line_on: raw.ideal_line_on,
            is_in_pit_lane: raw.is_in_pit_lane,
            surface_grip: raw.surface_grip,
            mandatory_pit_done: raw.mandatory_pit_done,
            wind_speed: raw.wind_speed,
            wind_direction: raw.wind_direction,
            is_setup_menu_visible: raw.is_setup_menu_visible,
            main_display_index: raw.main_display_index,
            secondary_display_index: raw.secondary_display_index,
            tc: raw.tc,
            tc_cut: raw.tc_cut,
            engine_map: raw.engine_map,
            abs: raw.abs,
            fuel_xlap: raw.fuel_xlap,
            rain_lights: raw.rain_lights,
            flashing_lights: raw.flashing_lights,
            lights_stage: raw.lights_stage,
            exhaust_temperature: raw.exhaust_temperature,
            wiper_lv: raw.wiper_lv,
            driver_stint_total_time_left: raw.driver_stint_total_time_left,
            driver_stint_time_left: raw.driver_stint_time_left,
            rain_tyres: raw.rain_tyres,
        }
    }
}

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct AcStaticData {
    pub sm_version: SimStringU16<15>,
    pub ac_version: SimStringU16<15>,
    pub number_of_sessions: i32,
    pub num_cars: i32,
    pub car_model: SimStringU16<33>,
    pub track: SimStringU16<33>,
    pub player_name: SimStringU16<33>,
    pub player_surname: SimStringU16<33>,
    pub player_nick: SimStringU16<33>,
    pub sector_count: i32,
    pub max_torque: f32,
    pub max_power: f32,
    pub max_rpm: i32,
    pub max_fuel: f32,
    pub suspension_max_travel: [f32; 4],
    pub tyre_radius: [f32; 4],
    pub max_turbo_boost: f32,
    pub _deprecated_1: f32,
    pub _deprecated_2: f32,
    pub penalties_enabled: i32,
    pub aid_fuel_rate: f32,
    pub aid_tire_rate: f32,
    pub aid_mechanical_damage: f32,
    pub aid_allow_tyre_blankets: i32,
    pub aid_stability: f32,
    pub aid_auto_clutch: i32,
    pub aid_auto_blip: i32,
    pub has_drs: i32,
    pub has_ers: i32,
    pub has_kers: i32,
    pub kers_max_j: f32,
    pub engine_brake_settings_count: i32,
    pub ers_power_controller_count: i32,
    pub track_spline_length: f32,
    pub track_configuration: SimStringU16<33>,
    pub ers_max_j: f32,
    pub is_timed_race: i32,
    pub has_extra_lap: i32,
    pub car_skin: SimStringU16<33>,
    pub reversed_grid_positions: i32,
    pub pit_window_start: i32,
    pub pit_window_end: i32,
    pub is_online: i32,
}

impl From<SPageFileStatic> for AcStaticData {
    fn from(raw: SPageFileStatic) -> Self {
        Self {
            sm_version: SimStringU16::from_u16_array(raw.sm_version),
            ac_version: SimStringU16::from_u16_array(raw.ac_version),
            number_of_sessions: raw.number_of_sessions,
            num_cars: raw.num_cars,
            car_model: SimStringU16::from_u16_array(raw.car_model),
            track: SimStringU16::from_u16_array(raw.track),
            player_name: SimStringU16::from_u16_array(raw.player_name),
            player_surname: SimStringU16::from_u16_array(raw.player_surname),
            player_nick: SimStringU16::from_u16_array(raw.player_nick),
            sector_count: raw.sector_count,
            max_torque: raw.max_torque,
            max_power: raw.max_power,
            max_rpm: raw.max_rpm,
            max_fuel: raw.max_fuel,
            suspension_max_travel: raw.suspension_max_travel,
            tyre_radius: raw.tyre_radius,
            max_turbo_boost: raw.max_turbo_boost,
            _deprecated_1: raw._deprecated_1,
            _deprecated_2: raw._deprecated_2,
            penalties_enabled: raw.penalties_enabled,
            aid_fuel_rate: raw.aid_fuel_rate,
            aid_tire_rate: raw.aid_tire_rate,
            aid_mechanical_damage: raw.aid_mechanical_damage,
            aid_allow_tyre_blankets: raw.aid_allow_tyre_blankets,
            aid_stability: raw.aid_stability,
            aid_auto_clutch: raw.aid_auto_clutch,
            aid_auto_blip: raw.aid_auto_blip,
            has_drs: raw.has_drs,
            has_ers: raw.has_ers,
            has_kers: raw.has_kers,
            kers_max_j: raw.kers_max_j,
            engine_brake_settings_count: raw.engine_brake_settings_count,
            ers_power_controller_count: raw.ers_power_controller_count,
            track_spline_length: raw.track_spline_length,
            track_configuration: SimStringU16::from_u16_array(raw.track_configuration),
            ers_max_j: raw.ers_max_j,
            is_timed_race: raw.is_timed_race,
            has_extra_lap: raw.has_extra_lap,
            car_skin: SimStringU16::from_u16_array(raw.car_skin),
            reversed_grid_positions: raw.reversed_grid_positions,
            pit_window_start: raw.pit_window_start,
            pit_window_end: raw.pit_window_end,
            is_online: raw.is_online,
        }
    }
}

// ── AC Evo ────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct AcEvoTyreState {
    pub tyre_compound_symbol: SimStringU16<33>,
    pub tyre_compound_name: SimStringU16<50>,
    pub tyre_compound_short: SimStringU16<5>,
    pub tyre_compound_color: SimStringU16<10>,
    pub is_wet_tyre: i32,
    pub tyre_surface_temp: [f32; 3],
    pub tyre_inner_temp: [f32; 3],
    pub tyre_core_temp: f32,
    pub tyre_pressure: f32,
    pub tyre_slip_ratio: f32,
    pub tyre_slip_angle: f32,
    pub tyre_nd_slip: f32,
    pub tyre_load: f32,
    pub tyre_dirt_level: f32,
    pub tyre_wear: f32,
    pub tyre_angular_speed: f32,
    pub suspension_travel: f32,
    pub camber: f32,
    pub rim_temp: f32,
    pub brake_disc_temp: f32,
    pub brake_disc_wear: f32,
    pub brake_temp: f32,
}

impl From<SMEvoTyreState> for AcEvoTyreState {
    fn from(raw: SMEvoTyreState) -> Self {
        Self {
            tyre_compound_symbol: SimStringU16::from_u16_array(raw.tyre_compound_symbol),
            tyre_compound_name: SimStringU16::from_u16_array(raw.tyre_compound_name),
            tyre_compound_short: SimStringU16::from_u16_array(raw.tyre_compound_short),
            tyre_compound_color: SimStringU16::from_u16_array(raw.tyre_compound_color),
            is_wet_tyre: raw.is_wet_tyre,
            tyre_surface_temp: raw.tyre_surface_temp,
            tyre_inner_temp: raw.tyre_inner_temp,
            tyre_core_temp: raw.tyre_core_temp,
            tyre_pressure: raw.tyre_pressure,
            tyre_slip_ratio: raw.tyre_slip_ratio,
            tyre_slip_angle: raw.tyre_slip_angle,
            tyre_nd_slip: raw.tyre_nd_slip,
            tyre_load: raw.tyre_load,
            tyre_dirt_level: raw.tyre_dirt_level,
            tyre_wear: raw.tyre_wear,
            tyre_angular_speed: raw.tyre_angular_speed,
            suspension_travel: raw.suspension_travel,
            camber: raw.camber,
            rim_temp: raw.rim_temp,
            brake_disc_temp: raw.brake_disc_temp,
            brake_disc_wear: raw.brake_disc_wear,
            brake_temp: raw.brake_temp,
        }
    }
}

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct AcPhysicsDataEvo {
    pub packet_id: i32,
    pub gas: f32,
    pub brake: f32,
    pub fuel: f32,
    pub gear: i32,
    pub rpms: i32,
    pub steer_angle: f32,
    pub speed_kmh: f32,
    pub velocity: [f32; 3],
    pub acc_g: [f32; 3],
    pub wheel_slip: [f32; 4],
    pub wheel_load: [f32; 4],
    pub wheels_pressure: [f32; 4],
    pub wheel_angular_speed: [f32; 4],
    pub tyre_wear: [f32; 4],
    pub tyre_dirty_level: [f32; 4],
    pub tyre_core_temperature: [f32; 4],
    pub camber_rad: [f32; 4],
    pub suspension_travel: [f32; 4],
    pub drs: f32,
    pub tc: f32,
    pub heading: f32,
    pub pitch: f32,
    pub roll: f32,
    pub cg_height: f32,
    pub car_damage: [f32; 5],
    pub number_of_tyres_out: i32,
    pub pit_limiter_on: i32,
    pub abs: f32,
    pub auto_shifter_on: i32,
    pub ride_height: [f32; 2],
    pub turbo_boost: f32,
    pub ballast: f32,
    pub air_density: f32,
    pub air_temp: f32,
    pub road_temp: f32,
    pub local_angular_vel: [f32; 3],
    pub final_ff: f32,
    pub engine_brake: i32,
    pub brake_temp: [f32; 4],
    pub clutch: f32,
    pub tyre_temp_i: [f32; 4],
    pub tyre_temp_m: [f32; 4],
    pub tyre_temp_o: [f32; 4],
    pub is_ai_controlled: i32,
    pub brake_bias: f32,
    pub local_velocity: [f32; 3],
    pub front_brake_compound: i32,
    pub rear_brake_compound: i32,
    pub pad_life: [f32; 4],
    pub disc_life: [f32; 4],
    pub ignition_on: i32,
    pub starter_engine_on: i32,
    pub is_engine_running: i32,
    pub kerb_vibration: f32,
    pub slip_vibrations: f32,
    pub g_vibrations: f32,
    pub abs_vibrations: f32,
}

impl From<SPageFilePhysicsEvo> for AcPhysicsDataEvo {
    fn from(raw: SPageFilePhysicsEvo) -> Self {
        Self {
            packet_id: raw.packet_id,
            gas: raw.gas,
            brake: raw.brake,
            fuel: raw.fuel,
            gear: raw.gear,
            rpms: raw.rpms,
            steer_angle: raw.steer_angle,
            speed_kmh: raw.speed_kmh,
            velocity: raw.velocity,
            acc_g: raw.acc_g,
            wheel_slip: raw.wheel_slip,
            wheel_load: raw.wheel_load,
            wheels_pressure: raw.wheels_pressure,
            wheel_angular_speed: raw.wheel_angular_speed,
            tyre_wear: raw.tyre_wear,
            tyre_dirty_level: raw.tyre_dirty_level,
            tyre_core_temperature: raw.tyre_core_temperature,
            camber_rad: raw.camber_rad,
            suspension_travel: raw.suspension_travel,
            drs: raw.drs,
            tc: raw.tc,
            heading: raw.heading,
            pitch: raw.pitch,
            roll: raw.roll,
            cg_height: raw.cg_height,
            car_damage: raw.car_damage,
            number_of_tyres_out: raw.number_of_tyres_out,
            pit_limiter_on: raw.pit_limiter_on,
            abs: raw.abs,
            auto_shifter_on: raw.auto_shifter_on,
            ride_height: raw.ride_height,
            turbo_boost: raw.turbo_boost,
            ballast: raw.ballast,
            air_density: raw.air_density,
            air_temp: raw.air_temp,
            road_temp: raw.road_temp,
            local_angular_vel: raw.local_angular_vel,
            final_ff: raw.final_ff,
            engine_brake: raw.engine_brake,
            brake_temp: raw.brake_temp,
            clutch: raw.clutch,
            tyre_temp_i: raw.tyre_temp_i,
            tyre_temp_m: raw.tyre_temp_m,
            tyre_temp_o: raw.tyre_temp_o,
            is_ai_controlled: raw.is_ai_controlled,
            brake_bias: raw.brake_bias,
            local_velocity: raw.local_velocity,
            front_brake_compound: raw.front_brake_compound,
            rear_brake_compound: raw.rear_brake_compound,
            pad_life: raw.pad_life,
            disc_life: raw.disc_life,
            ignition_on: raw.ignition_on,
            starter_engine_on: raw.starter_engine_on,
            is_engine_running: raw.is_engine_running,
            kerb_vibration: raw.kerb_vibration,
            slip_vibrations: raw.slip_vibrations,
            g_vibrations: raw.g_vibrations,
            abs_vibrations: raw.abs_vibrations,
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct AcGraphicsDataEvo {
    pub packet_id: i32,
    pub status: i32,
    pub session: i32,
    pub current_time: SimStringU16<15>,
    pub last_time: SimStringU16<15>,
    pub best_time: SimStringU16<15>,
    pub split: SimStringU16<15>,
    pub completed_laps: i32,
    pub position: i32,
    pub i_current_time: i32,
    pub i_last_time: i32,
    pub i_best_time: i32,
    pub session_time_left: f32,
    pub distance_traveled: f32,
    pub is_in_pit: i32,
    pub current_sector_index: i32,
    pub last_sector_time: i32,
    pub number_of_laps: i32,
    pub tyre_compound: SimStringU16<33>,
    pub normalized_car_position: f32,
    pub active_cars: i32,
    #[serde(skip)]
    pub car_coordinates: [[f32; 3]; 60],
    #[serde(skip)]
    pub car_id: [i32; 60],
    pub player_car_id: i32,
    pub penalty_time: f32,
    pub flag: i32,
    pub penalty: i32,
    pub ideal_line_on: i32,
    pub is_in_pit_lane: i32,
    pub surface_grip: f32,
    pub mandatory_pit_done: i32,
    pub wind_speed: f32,
    pub wind_direction: f32,
    pub tc: i32,
    pub tc_cut: i32,
    pub engine_map: i32,
    pub abs: i32,
    pub fuel_xlap: f32,
    pub rain_lights: i32,
    pub flashing_lights: i32,
    pub lights_stage: i32,
    pub exhaust_temperature: f32,
    pub wiper_lv: i32,
    pub driver_stint_total_time_left: i32,
    pub driver_stint_time_left: i32,
    pub rain_tyres: i32,
    pub session_index: i32,
    pub used_fuel: f32,
    pub delta_lap_time: SimStringU16<15>,
    pub i_delta_lap_time: i32,
    pub estimated_lap_time: SimStringU16<15>,
    pub i_estimated_lap_time: i32,
    pub is_delta_positive: i32,
    pub i_split: i32,
    pub is_valid_lap: i32,
    pub fuel_estimated_laps: f32,
    pub track_status: SimStringU16<33>,
    pub missing_mandatory_pits: i32,
    pub clock: f32,
    pub direction_lights_left: i32,
    pub direction_lights_right: i32,
    pub global_yellow: i32,
    pub global_yellow_1: i32,
    pub global_yellow_2: i32,
    pub global_yellow_3: i32,
    pub global_white: i32,
    pub global_green: i32,
    pub global_chequered: i32,
    pub global_red: i32,
    pub mfd_tyre_set: i32,
    pub mfd_fuel_to_add: f32,
    pub mfd_tyre_pressure_lf: f32,
    pub mfd_tyre_pressure_rf: f32,
    pub mfd_tyre_pressure_lr: f32,
    pub mfd_tyre_pressure_rr: f32,
    pub track_grip_status: i32,
    pub rain_intensity: i32,
    pub rain_intensity_in_10min: i32,
    pub rain_intensity_in_30min: i32,
    pub current_tyre_set: i32,
    pub strategy_tyre_set: i32,
    pub tyres: [AcEvoTyreState; 4],
}

impl From<SPageFileGraphicsEvo> for AcGraphicsDataEvo {
    fn from(raw: SPageFileGraphicsEvo) -> Self {
        Self {
            packet_id: raw.packet_id,
            status: raw.status,
            session: raw.session,
            current_time: SimStringU16::from_u16_array(raw.current_time),
            last_time: SimStringU16::from_u16_array(raw.last_time),
            best_time: SimStringU16::from_u16_array(raw.best_time),
            split: SimStringU16::from_u16_array(raw.split),
            completed_laps: raw.completed_laps,
            position: raw.position,
            i_current_time: raw.i_current_time,
            i_last_time: raw.i_last_time,
            i_best_time: raw.i_best_time,
            session_time_left: raw.session_time_left,
            distance_traveled: raw.distance_traveled,
            is_in_pit: raw.is_in_pit,
            current_sector_index: raw.current_sector_index,
            last_sector_time: raw.last_sector_time,
            number_of_laps: raw.number_of_laps,
            tyre_compound: SimStringU16::from_u16_array(raw.tyre_compound),
            normalized_car_position: raw.normalized_car_position,
            active_cars: raw.active_cars,
            car_coordinates: raw.car_coordinates,
            car_id: raw.car_id,
            player_car_id: raw.player_car_id,
            penalty_time: raw.penalty_time,
            flag: raw.flag,
            penalty: raw.penalty,
            ideal_line_on: raw.ideal_line_on,
            is_in_pit_lane: raw.is_in_pit_lane,
            surface_grip: raw.surface_grip,
            mandatory_pit_done: raw.mandatory_pit_done,
            wind_speed: raw.wind_speed,
            wind_direction: raw.wind_direction,
            tc: raw.tc,
            tc_cut: raw.tc_cut,
            engine_map: raw.engine_map,
            abs: raw.abs,
            fuel_xlap: raw.fuel_xlap,
            rain_lights: raw.rain_lights,
            flashing_lights: raw.flashing_lights,
            lights_stage: raw.lights_stage,
            exhaust_temperature: raw.exhaust_temperature,
            wiper_lv: raw.wiper_lv,
            driver_stint_total_time_left: raw.driver_stint_total_time_left,
            driver_stint_time_left: raw.driver_stint_time_left,
            rain_tyres: raw.rain_tyres,
            session_index: raw.session_index,
            used_fuel: raw.used_fuel,
            delta_lap_time: SimStringU16::from_u16_array(raw.delta_lap_time),
            i_delta_lap_time: raw.i_delta_lap_time,
            estimated_lap_time: SimStringU16::from_u16_array(raw.estimated_lap_time),
            i_estimated_lap_time: raw.i_estimated_lap_time,
            is_delta_positive: raw.is_delta_positive,
            i_split: raw.i_split,
            is_valid_lap: raw.is_valid_lap,
            fuel_estimated_laps: raw.fuel_estimated_laps,
            track_status: SimStringU16::from_u16_array(raw.track_status),
            missing_mandatory_pits: raw.missing_mandatory_pits,
            clock: raw.clock,
            direction_lights_left: raw.direction_lights_left,
            direction_lights_right: raw.direction_lights_right,
            global_yellow: raw.global_yellow,
            global_yellow_1: raw.global_yellow_1,
            global_yellow_2: raw.global_yellow_2,
            global_yellow_3: raw.global_yellow_3,
            global_white: raw.global_white,
            global_green: raw.global_green,
            global_chequered: raw.global_chequered,
            global_red: raw.global_red,
            mfd_tyre_set: raw.mfd_tyre_set,
            mfd_fuel_to_add: raw.mfd_fuel_to_add,
            mfd_tyre_pressure_lf: raw.mfd_tyre_pressure_lf,
            mfd_tyre_pressure_rf: raw.mfd_tyre_pressure_rf,
            mfd_tyre_pressure_lr: raw.mfd_tyre_pressure_lr,
            mfd_tyre_pressure_rr: raw.mfd_tyre_pressure_rr,
            track_grip_status: raw.track_grip_status,
            rain_intensity: raw.rain_intensity,
            rain_intensity_in_10min: raw.rain_intensity_in_10min,
            rain_intensity_in_30min: raw.rain_intensity_in_30min,
            current_tyre_set: raw.current_tyre_set,
            strategy_tyre_set: raw.strategy_tyre_set,
            tyres: raw.tyres.map(AcEvoTyreState::from),
        }
    }
}

#[derive(Debug, Clone, Default, serde::Serialize)]
pub struct AcStaticDataEvo {
    pub sm_version: SimStringU16<15>,
    pub ac_version: SimStringU16<15>,
    pub number_of_sessions: i32,
    pub num_cars: i32,
    pub car_model: SimStringU16<33>,
    pub track: SimStringU16<33>,
    pub player_name: SimStringU16<33>,
    pub player_surname: SimStringU16<33>,
    pub player_nick: SimStringU16<33>,
    pub sector_count: i32,
    pub max_torque: f32,
    pub max_power: f32,
    pub max_rpm: i32,
    pub max_fuel: f32,
    pub suspension_max_travel: [f32; 4],
    pub tyre_radius: [f32; 4],
    pub max_turbo_boost: f32,
    pub penalties_enabled: i32,
    pub aid_fuel_rate: f32,
    pub aid_tire_rate: f32,
    pub aid_mechanical_damage: f32,
    pub aid_allow_tyre_blankets: i32,
    pub aid_stability: f32,
    pub aid_auto_clutch: i32,
    pub aid_auto_blip: i32,
    pub pit_window_start: i32,
    pub pit_window_end: i32,
    pub is_online: i32,
    pub dry_tyres_name: SimStringU16<33>,
    pub wet_tyres_name: SimStringU16<33>,
}

impl From<SPageFileStaticEvo> for AcStaticDataEvo {
    fn from(raw: SPageFileStaticEvo) -> Self {
        Self {
            sm_version: SimStringU16::from_u16_array(raw.sm_version),
            ac_version: SimStringU16::from_u16_array(raw.ac_version),
            number_of_sessions: raw.number_of_sessions,
            num_cars: raw.num_cars,
            car_model: SimStringU16::from_u16_array(raw.car_model),
            track: SimStringU16::from_u16_array(raw.track),
            player_name: SimStringU16::from_u16_array(raw.player_name),
            player_surname: SimStringU16::from_u16_array(raw.player_surname),
            player_nick: SimStringU16::from_u16_array(raw.player_nick),
            sector_count: raw.sector_count,
            max_torque: raw.max_torque,
            max_power: raw.max_power,
            max_rpm: raw.max_rpm,
            max_fuel: raw.max_fuel,
            suspension_max_travel: raw.suspension_max_travel,
            tyre_radius: raw.tyre_radius,
            max_turbo_boost: raw.max_turbo_boost,
            penalties_enabled: raw.penalties_enabled,
            aid_fuel_rate: raw.aid_fuel_rate,
            aid_tire_rate: raw.aid_tire_rate,
            aid_mechanical_damage: raw.aid_mechanical_damage,
            aid_allow_tyre_blankets: raw.aid_allow_tyre_blankets,
            aid_stability: raw.aid_stability,
            aid_auto_clutch: raw.aid_auto_clutch,
            aid_auto_blip: raw.aid_auto_blip,
            pit_window_start: raw.pit_window_start,
            pit_window_end: raw.pit_window_end,
            is_online: raw.is_online,
            dry_tyres_name: SimStringU16::from_u16_array(raw.dry_tyres_name),
            wet_tyres_name: SimStringU16::from_u16_array(raw.wet_tyres_name),
        }
    }
}
