use serde::Deserialize;

#[derive(Deserialize)]
pub struct VarDef {
    pub name: String,
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(default = "default_count")]
    pub count: u32,
    #[serde(default)]
    pub unit: String,
    #[serde(default)]
    pub desc: String,
}

fn default_count() -> u32 {
    1
}

#[derive(Deserialize)]
struct VarFile {
    var: Vec<VarDef>,
}

pub fn camel_to_snake(name: &str) -> String {
    let mut out = String::new();

    let chars: Vec<char> = name.chars().collect();

    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() {
            let prev_lower = i > 0 && chars[i - 1].is_lowercase();
            let next_lower = i + 1 < chars.len() && chars[i + 1].is_lowercase();
            let prev_upper = i > 0 && chars[i - 1].is_uppercase();

            if i > 0 && (prev_lower || (next_lower && prev_upper)) {
                out.push('_');
            }

            out.push(c.to_lowercase().next().unwrap());
        } else {
            out.push(c);
        }
    }

    out
}

fn rust_type(type_: &str, count: u32) -> String {
    if count > 1 {
        match type_ {
            "f32" => "Vec<f32>",
            "f64" => "Vec<f64>",
            "i32" => "Vec<i32>",
            "bool" => "Vec<bool>",
            _ => "Vec<i32>",
        }
        .to_string()
    } else {
        type_.to_string()
    }
}

fn extract_expr(type_: &str, count: u32, name: &str) -> String {
    if count > 1 {
        let variant = match type_ {
            "f32" => "FloatArray",
            "f64" => "DoubleArray",
            "bool" => "BoolArray",
            _ => "IntArray",
        };

        format!(
            r#"match vars.get("{}") {{ Some(crate::types::TelemetryValue::{}(v)) => v.clone(), _ => Vec::new() }}"#,
            name, variant
        )
    } else {
        let (variant, default) = match type_ {
            "f32" => ("Float", "0.0"),
            "f64" => ("Double", "0.0"),
            "i32" => ("Int", "0"),
            "bool" => ("Bool", "false"),
            _ => ("Int", "0"),
        };

        format!(
            r#"match vars.get("{}") {{ Some(crate::types::TelemetryValue::{}(v)) => *v, _ => {} }}"#,
            name, variant, default
        )
    }
}

/// Generate `src/iracing/vars.rs` from a slice of variable definitions.
pub fn generate_from_defs(vars: &[VarDef]) -> String {
    let mut out = String::new();

    out.push_str("// AUTOGENERATED FILE. Do not edit manually.\n");
    out.push_str("// To regenerate: run iracing_type_gen with iRacing open.\n");
    out.push_str(
        "//   cargo run --manifest-path tools/iracing_type_gen/Cargo.toml -- src/iracing/types.rs\n\n",
    );

    out.push_str("use std::collections::HashMap;\n\n");

    out.push_str("/// Owned telemetry frame from iRacing. All fields populated in one SHM read.\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub struct IracingFrame {\n");

    for v in vars {
        let field = camel_to_snake(&v.name);

        let unit_str = if v.unit.is_empty() {
            String::new()
        } else {
            format!(" [{}]", v.unit)
        };

        out.push_str(&format!("    /// {}{}\n", v.desc, unit_str));
        out.push_str(&format!(
            "    pub {}: {},\n",
            field,
            rust_type(&v.type_, v.count)
        ));
    }

    out.push_str("}\n\n");

    out.push_str("impl IracingFrame {\n");
    out.push_str("    pub(crate) fn from_vars(vars: &HashMap<String, crate::types::TelemetryValue>) -> Self {\n");
    out.push_str("        Self {\n");

    for v in vars {
        let field = camel_to_snake(&v.name);

        out.push_str(&format!(
            "            {}: {},\n",
            field,
            extract_expr(&v.type_, v.count, &v.name)
        ));
    }

    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    pub(crate) fn from_connection(conn: &crate::iracing::connection::IRsdkConnection) -> Self {\n");
    out.push_str("        Self::from_vars(&conn.read_all_variables())\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Generate from a TOML string (used by tests).
pub fn generate(toml_str: &str) -> String {
    let file: VarFile = toml::from_str(toml_str).expect("invalid toml");

    generate_from_defs(&file.var)
}
