use iracing_type_gen::{
    VarDef, catalogue_to_toml, generate_from_defs, merge_defs, parse_catalogue,
};
use std::fs;
use std::path::Path;
use windows_sys::Win32::Foundation::{CloseHandle, INVALID_HANDLE_VALUE};
use windows_sys::Win32::System::Memory::{FILE_MAP_READ, MapViewOfFile, OpenFileMappingW};

const SHM_MEM_MAP_FILE: &str = "Local\\IRSDKMemMapFileName";

#[repr(C)]
struct irsdk_varBuf {
    _tick_count: i32,
    _buf_offset: i32,
    _pad: [i32; 2],
}

#[repr(C)]
struct irsdk_header {
    ver: i32,
    _status: i32,
    _tick_rate: i32,
    _session_info_update: i32,
    _session_info_len: i32,
    _session_info_offset: i32,
    num_vars: i32,
    var_header_offset: i32,
    _num_buf: i32,
    _buf_len: i32,
    _pad: [i32; 2],
    _var_buf: [irsdk_varBuf; 4],
}

#[repr(C)]
struct irsdk_varHeader {
    type_: i32,
    _offset: i32,
    count: i32,
    _count_as_char: u8,
    _pad: [u8; 3],
    name: [u8; 32],
    desc: [u8; 64],
    unit: [u8; 32],
}

fn parse_c_str(bytes: &[u8]) -> String {
    let len = bytes.iter().position(|&x| x == 0).unwrap_or(bytes.len());
    let (decoded, _, _) = encoding_rs::WINDOWS_1252.decode(&bytes[..len]);
    decoded.into_owned()
}

fn read_iracing_variables() -> Result<Vec<VarDef>, String> {
    unsafe {
        let map_name: Vec<u16> = SHM_MEM_MAP_FILE
            .encode_utf16()
            .chain(std::iter::once(0))
            .collect();

        let h_map = OpenFileMappingW(FILE_MAP_READ, 0, map_name.as_ptr());
        if h_map.is_null() || h_map == INVALID_HANDLE_VALUE {
            return Err("iRacing shared memory not found. Is iRacing running?".to_string());
        }

        let view = MapViewOfFile(h_map, FILE_MAP_READ, 0, 0, 0);
        if view.Value.is_null() {
            CloseHandle(h_map);
            return Err("Failed to map view of iRacing shared memory.".to_string());
        }

        let header = std::ptr::read_unaligned(view.Value as *const irsdk_header);
        if header.ver <= 0 || header.ver > 10 || header.num_vars <= 0 {
            CloseHandle(h_map);
            return Err(format!(
                "Invalid iRacing telemetry header (ver={}, num_vars={})",
                header.ver, header.num_vars
            ));
        }

        let num = header.num_vars as usize;
        let var_offset = header.var_header_offset as usize;
        let element_size = std::mem::size_of::<irsdk_varHeader>();

        let mut vars = Vec::with_capacity(num);

        for i in 0..num {
            let offset = var_offset + i * element_size;
            let var_header_ptr = (view.Value as *const u8).add(offset) as *const irsdk_varHeader;
            let var_header = std::ptr::read_unaligned(var_header_ptr);

            let name = parse_c_str(&var_header.name);
            let desc = parse_c_str(&var_header.desc);
            let unit = parse_c_str(&var_header.unit);

            let rust_type = match var_header.type_ {
                4 => "f32",     // Float
                5 => "f64",     // Double
                2 | 3 => "i32", // Int | BitField
                1 => "bool",    // Bool
                0 => "i32",     // Char -> represented as i32 in vars
                _ => "i32",
            }
            .to_string();

            vars.push(VarDef {
                name,
                type_: rust_type,
                count: var_header.count as u32,
                unit,
                desc,
            });
        }

        CloseHandle(h_map);

        Ok(vars)
    }
}

fn write_dummy_placeholder(output_path: &str) -> std::io::Result<()> {
    let dummy_content = r#"// AUTOGENERATED DUMMY PLACEHOLDER. Do not edit manually.
// This is a placeholder file created to allow compilation when iRacing is not running.
use std::collections::HashMap;

#[derive(Debug, Clone, Copy)]
pub struct IracingOffset {
    pub offset: usize,
    pub count: usize,
}

#[derive(Debug, Clone, Default)]
pub struct IracingOffsets {}

impl IracingOffsets {
    pub(crate) fn resolve(_vars: &HashMap<String, crate::iracing::structs::irsdk_varHeader>) -> Self {
        Self {}
    }
}

#[derive(Debug, Clone)]
pub struct IracingFrame {}

impl IracingFrame {
    pub(crate) fn from_raw(_buf: *const u8, _offsets: &IracingOffsets) -> Self {
        Self {}
    }
}
"#;
    fs::write(output_path, dummy_content)
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() != 3 {
        eprintln!("Usage: iracing_type_gen <catalogue.toml> <output.rs>");
        eprintln!("  Generates <output.rs> from the catalogue.");
        eprintln!("  With iRacing running, the session is merged into the catalogue first.");
        std::process::exit(1);
    }

    let catalogue_path = &args[1];
    let output_path = &args[2];

    // A missing output file would stop the crate compiling, and the operator
    // may be here precisely because of that. Put a placeholder in first so a
    // failure further down never leaves the tree unbuildable.
    if !Path::new(output_path).exists() {
        println!("{output_path} is missing. Writing a placeholder first.");

        if let Err(error) = write_dummy_placeholder(output_path) {
            eprintln!("Warning: cannot write placeholder: {error}");
        }
    }

    let catalogue_src = fs::read_to_string(catalogue_path).unwrap_or_default();

    let catalogue = match parse_catalogue(&catalogue_src) {
        Ok(vars) => vars,
        Err(error) => {
            eprintln!("Cannot parse {catalogue_path}: {error}");
            std::process::exit(1);
        }
    };

    let vars = match read_iracing_variables() {
        Ok(session) => merge_session(catalogue_path, &catalogue, &session),
        Err(error) => {
            if catalogue.is_empty() {
                eprintln!("Error: {error}");
                eprintln!(
                    "The catalogue is empty, so there is nothing to generate from.                      Start iRacing and enter a session to bootstrap it."
                );
                std::process::exit(1);
            }

            println!("{error}");
            println!(
                "Generating from the catalogue alone ({} variables).",
                catalogue.len()
            );

            catalogue
        }
    };

    fs::write(output_path, generate_from_defs(&vars)).unwrap_or_else(|error| {
        eprintln!("Cannot write {output_path}: {error}");
        std::process::exit(1);
    });

    println!("Generated {output_path} ({} variables)", vars.len());
}

/// Fold the live session into the catalogue and write it back, reporting what
/// changed. The catalogue only ever grows: a variable the current car lacks is
/// still published by some other car, so it is kept rather than dropped.
fn merge_session(catalogue_path: &str, catalogue: &[VarDef], session: &[VarDef]) -> Vec<VarDef> {
    let (merged, report) = merge_defs(catalogue, session);

    println!(
        "Session declares {} variables; catalogue held {}, now {}.",
        session.len(),
        catalogue.len(),
        merged.len()
    );

    if !report.added.is_empty() {
        println!("Added {}: {}", report.added.len(), report.added.join(", "));
    }

    if !report.redefined.is_empty() {
        println!(
            "Redefined {}: {}",
            report.redefined.len(),
            report.redefined.join(", ")
        );
    }

    if !report.absent.is_empty() {
        println!(
            "Kept {} not exposed by this car (normal — the list is per car).",
            report.absent.len()
        );
    }

    fs::write(catalogue_path, catalogue_to_toml(&merged)).unwrap_or_else(|error| {
        eprintln!("Cannot write {catalogue_path}: {error}");
        std::process::exit(1);
    });

    merged
}
