use iracing_type_gen::{VarDef, generate_from_defs};
use std::fs;
use std::path::Path;
use windows_sys::Win32::Foundation::{CloseHandle, INVALID_HANDLE_VALUE};
use windows_sys::Win32::System::Memory::{FILE_MAP_READ, MapViewOfFile, OpenFileMappingW};

const SHM_MEM_MAP_FILE: &str = "Local\\IRSDKMemMapFileName";

#[repr(C)]
struct irsdk_varBuf {
    _tick_count: i32,
    _buf_offset: i32,
    _pad: [i32; 2],
}

#[repr(C)]
struct irsdk_header {
    ver: i32,
    _status: i32,
    _tick_rate: i32,
    _session_info_update: i32,
    _session_info_len: i32,
    _session_info_offset: i32,
    num_vars: i32,
    var_header_offset: i32,
    _num_buf: i32,
    _buf_len: i32,
    _pad: [i32; 2],
    _var_buf: [irsdk_varBuf; 4],
}

#[repr(C)]
struct irsdk_varHeader {
    type_: i32,
    _offset: i32,
    count: i32,
    _count_as_char: u8,
    _pad: [u8; 3],
    name: [u8; 32],
    desc: [u8; 64],
    unit: [u8; 32],
}

fn parse_c_str(bytes: &[u8]) -> String {
    let len = bytes.iter().position(|&x| x == 0).unwrap_or(bytes.len());
    let (decoded, _, _) = encoding_rs::WINDOWS_1252.decode(&bytes[..len]);
    decoded.into_owned()
}

fn read_iracing_variables() -> Result<Vec<VarDef>, String> {
    unsafe {
        let map_name: Vec<u16> = SHM_MEM_MAP_FILE
            .encode_utf16()
            .chain(std::iter::once(0))
            .collect();

        let h_map = OpenFileMappingW(FILE_MAP_READ, 0, map_name.as_ptr());
        if h_map.is_null() || h_map == INVALID_HANDLE_VALUE {
            return Err("iRacing shared memory not found. Is iRacing running?".to_string());
        }

        let view = MapViewOfFile(h_map, FILE_MAP_READ, 0, 0, 0);
        if view.Value.is_null() {
            CloseHandle(h_map);
            return Err("Failed to map view of iRacing shared memory.".to_string());
        }

        let header = std::ptr::read_unaligned(view.Value as *const irsdk_header);
        if header.ver <= 0 || header.ver > 10 || header.num_vars <= 0 {
            CloseHandle(h_map);
            return Err(format!(
                "Invalid iRacing telemetry header (ver={}, num_vars={})",
                header.ver, header.num_vars
            ));
        }

        let num = header.num_vars as usize;
        let var_offset = header.var_header_offset as usize;
        let element_size = std::mem::size_of::<irsdk_varHeader>();

        let mut vars = Vec::with_capacity(num);

        for i in 0..num {
            let offset = var_offset + i * element_size;
            let var_header_ptr = (view.Value as *const u8).add(offset) as *const irsdk_varHeader;
            let var_header = std::ptr::read_unaligned(var_header_ptr);

            let name = parse_c_str(&var_header.name);
            let desc = parse_c_str(&var_header.desc);
            let unit = parse_c_str(&var_header.unit);

            let rust_type = match var_header.type_ {
                4 => "f32",     // Float
                5 => "f64",     // Double
                2 | 3 => "i32", // Int | BitField
                1 => "bool",    // Bool
                0 => "i32",     // Char -> represented as i32 in vars
                _ => "i32",
            }
            .to_string();

            vars.push(VarDef {
                name,
                type_: rust_type,
                count: var_header.count as u32,
                unit,
                desc,
            });
        }

        CloseHandle(h_map);

        Ok(vars)
    }
}

fn write_dummy_placeholder(output_path: &str) -> std::io::Result<()> {
    let dummy_content = r#"// AUTOGENERATED DUMMY PLACEHOLDER. Do not edit manually.
// This is a placeholder file created to allow compilation when iRacing is not running.
use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct IracingFrame {}

impl IracingFrame {
    pub(crate) fn from_vars(_vars: &HashMap<String, crate::types::TelemetryValue>) -> Self {
        Self {}
    }
    pub(crate) fn from_connection(_conn: &crate::iracing::connection::IRsdkConnection) -> Self {
        Self {}
    }
}
"#;
    fs::write(output_path, dummy_content)
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    if args.len() != 2 {
        eprintln!("Usage: iracing_type_gen <output.rs>");
        eprintln!("  iRacing must be running.");
        std::process::exit(1);
    }

    let output_path = &args[1];
    let output_path_obj = Path::new(output_path);

    // 1. If output file is missing, immediately write a placeholder so the project can compile in normal mode!
    if !output_path_obj.exists() {
        println!(
            "Types file is missing. Creating a dummy placeholder at {}",
            output_path
        );
        if let Err(e) = write_dummy_placeholder(output_path) {
            eprintln!("Warning: Failed to write placeholder: {}", e);
        }
    }

    // 2. Connect to running iRacing session
    let mut vars = match read_iracing_variables() {
        Ok(v) => v,
        Err(e) => {
            eprintln!("Error: {}", e);
            eprintln!("iRacing must be running when codegen is executed.");
            // We exit here, but we already created a placeholder if the file was missing, so compilation won't fail!
            std::process::exit(1);
        }
    };

    vars.sort_by(|a, b| a.name.cmp(&b.name));

    let output = generate_from_defs(&vars);

    fs::write(output_path, output).unwrap_or_else(|e| {
        eprintln!("Cannot write {}: {}", output_path, e);
        std::process::exit(1);
    });

    println!("Generated {} ({} variables)", output_path, vars.len());
}
