// AUTOGENERATED FILE. Do not edit manually.
// To regenerate: run codegen with iRacing open.
//   cargo run --manifest-path tools/codegen/Cargo.toml -- src/iracing/vars.rs

use std::collections::HashMap;

/// Owned telemetry frame from iRacing. All fields populated in one SHM read.
#[derive(Debug, Clone)]
pub struct IracingFrame {
    /// Density of air at start/finish line [kg/m^3]
    pub air_density: f32,
    /// Pressure of air at start/finish line [Pa]
    pub air_pressure: f32,
    /// Temperature of air at start/finish line [C]
    pub air_temp: f32,
    /// 0=brake released to 1=max pedal force [%]
    pub brake: f32,
    /// true if abs is currently reducing brake force pressure
    pub brake_ab_sactive: bool,
    /// Raw brake input 0=brake released to 1=max pedal force [%]
    pub brake_raw: f32,
    /// Active camera number
    pub cam_camera_number: i32,
    /// State of camera system [irsdk_CameraState]
    pub cam_camera_state: i32,
    /// Active camera's focus car index
    pub cam_car_idx: i32,
    /// Active camera group number
    pub cam_group_number: i32,
    /// Distance to first car in front of player in meters [m]
    pub car_dist_ahead: f32,
    /// Distance to first car behind player in meters [m]
    pub car_dist_behind: f32,
    /// Cars best lap number
    pub car_idx_best_lap_num: Vec<i32>,
    /// Cars best lap time [s]
    pub car_idx_best_lap_time: Vec<f32>,
    /// Cars class id by car index
    pub car_idx_class: Vec<i32>,
    /// Cars class position in race by car index
    pub car_idx_class_position: Vec<i32>,
    /// Estimated time to reach current location on track [s]
    pub car_idx_est_time: Vec<f32>,
    /// Race time behind leader or fastest lap time otherwise [s]
    pub car_idx_f2time: Vec<f32>,
    /// How many fast repairs each car has used
    pub car_idx_fast_repairs_used: Vec<i32>,
    /// -1=reverse  0=neutral  1..n=current gear by car index
    pub car_idx_gear: Vec<i32>,
    /// Laps started by car index
    pub car_idx_lap: Vec<i32>,
    /// Laps completed by car index
    pub car_idx_lap_completed: Vec<i32>,
    /// Percentage distance around lap by car index [%]
    pub car_idx_lap_dist_pct: Vec<f32>,
    /// Cars last lap time [s]
    pub car_idx_last_lap_time: Vec<f32>,
    /// On pit road between the cones by car index
    pub car_idx_on_pit_road: Vec<bool>,
    /// Push2Pass count of usage (or remaining in Race)
    pub car_idx_p2p_count: Vec<i32>,
    /// Push2Pass active or not
    pub car_idx_p2p_status: Vec<bool>,
    /// Pacing status flags for each car [irsdk_PaceFlags]
    pub car_idx_pace_flags: Vec<i32>,
    /// What line cars are pacing in  or -1 if not pacing
    pub car_idx_pace_line: Vec<i32>,
    /// What row cars are pacing in  or -1 if not pacing
    pub car_idx_pace_row: Vec<i32>,
    /// Cars position in race by car index
    pub car_idx_position: Vec<i32>,
    /// Cars Qual tire compound
    pub car_idx_qual_tire_compound: Vec<i32>,
    /// Cars Qual tire compound is locked-in
    pub car_idx_qual_tire_compound_locked: Vec<bool>,
    /// Engine rpm by car index [revs/min]
    pub car_idx_rpm: Vec<f32>,
    /// Session flags for each player [irsdk_Flags]
    pub car_idx_session_flags: Vec<i32>,
    /// Steering wheel angle by car index [rad]
    pub car_idx_steer: Vec<f32>,
    /// Cars current tire compound
    pub car_idx_tire_compound: Vec<i32>,
    /// Track surface type by car index [irsdk_TrkLoc]
    pub car_idx_track_surface: Vec<i32>,
    /// Track surface material type by car index [irsdk_TrkSurf]
    pub car_idx_track_surface_material: Vec<i32>,
    /// Notify if car is to the left or right of driver [irsdk_CarLeftRight]
    pub car_left_right: i32,
    /// Communications average latency [s]
    pub chan_avg_latency: f32,
    /// Communications server clock skew [s]
    pub chan_clock_skew: f32,
    /// Communications latency [s]
    pub chan_latency: f32,
    /// Partner communications quality [%]
    pub chan_partner_quality: f32,
    /// Communications quality [%]
    pub chan_quality: f32,
    /// 0=disengaged to 1=fully engaged [%]
    pub clutch: f32,
    /// Raw clutch input 0=disengaged to 1=fully engaged [%]
    pub clutch_raw: f32,
    /// Percent of available time bg thread took with a 1 sec avg [%]
    pub cpu_usage_bg: f32,
    /// Percent of available time fg thread took with a 1 sec avg [%]
    pub cpu_usage_fg: f32,
    /// Number of team drivers who have run a stint
    pub dc_drivers_so_far: i32,
    /// Status of driver change lap requirements
    pub dc_lap_status: i32,
    /// Default units for the user interface 0 = english 1 = metric
    pub display_units: i32,
    /// Driver activated flag
    pub driver_marker: bool,
    /// Engine0Engine rpm [revs/min]
    pub engine0_rpm: f32,
    /// Bitfield for warning lights [irsdk_EngineWarnings]
    pub engine_warnings: i32,
    /// Indicate action the reset key will take 0 enter 1 exit 2 reset
    pub enter_exit_reset: i32,
    /// How many fast repairs left  255 is unlimited
    pub fast_repair_available: i32,
    /// How many fast repairs used so far
    pub fast_repair_used: i32,
    /// Fog level at start/finish line [%]
    pub fog_level: f32,
    /// Average frames per second [fps]
    pub frame_rate: f32,
    /// How many front tire sets are remaining  255 is unlimited
    pub front_tire_sets_available: i32,
    /// How many front tire sets used so far
    pub front_tire_sets_used: i32,
    /// Liters of fuel remaining [l]
    pub fuel_level: f32,
    /// Percent fuel remaining [%]
    pub fuel_level_pct: f32,
    /// Engine fuel pressure [bar]
    pub fuel_press: f32,
    /// Engine fuel used instantaneous [kg/h]
    pub fuel_use_per_hour: f32,
    /// -1=reverse  0=neutral  1..n=current gear
    pub gear: i32,
    /// Percent of available time gpu took with a 1 sec avg [%]
    pub gpu_usage: f32,
    /// Raw handbrake input 0=handbrake released to 1=max force [%]
    pub handbrake_raw: f32,
    /// 0=disk based telemetry file not being written  1=being written
    pub is_disk_logging_active: bool,
    /// 0=disk based telemetry turned off  1=turned on
    pub is_disk_logging_enabled: bool,
    /// 1=Garage screen is visible
    pub is_garage_visible: bool,
    /// 1=Car in garage physics running
    pub is_in_garage: bool,
    /// 1=Car on track physics running with player in car
    pub is_on_track: bool,
    /// 1=Car on track physics running
    pub is_on_track_car: bool,
    /// 0=replay not playing  1=replay playing
    pub is_replay_playing: bool,
    /// How many left front tires are remaining  255 is unlimited
    pub lf_tires_available: i32,
    /// How many left front tires used so far
    pub lf_tires_used: i32,
    /// LF brake line pressure [bar]
    pub l_fbrake_line_press: f32,
    /// LF tire cold pressure  as set in the garage [kPa]
    pub l_fcold_pressure: f32,
    /// LF distance tire traveled since being placed on car [m]
    pub l_fodometer: f32,
    /// LF shock deflection [m]
    pub l_fshock_defl: f32,
    /// LF shock deflection at 360 Hz [m]
    pub l_fshock_defl_st: Vec<f32>,
    /// LF shock velocity [m/s]
    pub l_fshock_vel: f32,
    /// LF shock velocity at 360 Hz [m/s]
    pub l_fshock_vel_st: Vec<f32>,
    /// LF tire left carcass temperature [C]
    pub l_ftemp_cl: f32,
    /// LF tire middle carcass temperature [C]
    pub l_ftemp_cm: f32,
    /// LF tire right carcass temperature [C]
    pub l_ftemp_cr: f32,
    /// LF tire left percent tread remaining [%]
    pub l_fwear_l: f32,
    /// LF tire middle percent tread remaining [%]
    pub l_fwear_m: f32,
    /// LF tire right percent tread remaining [%]
    pub l_fwear_r: f32,
    /// How many left rear tires are remaining  255 is unlimited
    pub lr_tires_available: i32,
    /// How many left rear tires used so far
    pub lr_tires_used: i32,
    /// LR brake line pressure [bar]
    pub l_rbrake_line_press: f32,
    /// LR tire cold pressure  as set in the garage [kPa]
    pub l_rcold_pressure: f32,
    /// LR distance tire traveled since being placed on car [m]
    pub l_rodometer: f32,
    /// LR shock deflection [m]
    pub l_rshock_defl: f32,
    /// LR shock deflection at 360 Hz [m]
    pub l_rshock_defl_st: Vec<f32>,
    /// LR shock velocity [m/s]
    pub l_rshock_vel: f32,
    /// LR shock velocity at 360 Hz [m/s]
    pub l_rshock_vel_st: Vec<f32>,
    /// LR tire left carcass temperature [C]
    pub l_rtemp_cl: f32,
    /// LR tire middle carcass temperature [C]
    pub l_rtemp_cm: f32,
    /// LR tire right carcass temperature [C]
    pub l_rtemp_cr: f32,
    /// LR tire left percent tread remaining [%]
    pub l_rwear_l: f32,
    /// LR tire middle percent tread remaining [%]
    pub l_rwear_m: f32,
    /// LR tire right percent tread remaining [%]
    pub l_rwear_r: f32,
    /// Laps started count
    pub lap: i32,
    /// Players best lap number
    pub lap_best_lap: i32,
    /// Players best lap time [s]
    pub lap_best_lap_time: f32,
    /// Player last lap in best N average lap time
    pub lap_best_n_lap_lap: i32,
    /// Player best N average lap time [s]
    pub lap_best_n_lap_time: f32,
    /// Laps completed count
    pub lap_completed: i32,
    /// Estimate of players current lap time as shown in F3 box [s]
    pub lap_current_lap_time: f32,
    /// Delta time for best lap [s]
    pub lap_delta_to_best_lap: f32,
    /// Rate of change of delta time for best lap [s/s]
    pub lap_delta_to_best_lap_dd: f32,
    /// Delta time for best lap is valid
    pub lap_delta_to_best_lap_ok: bool,
    /// Delta time for optimal lap [s]
    pub lap_delta_to_optimal_lap: f32,
    /// Rate of change of delta time for optimal lap [s/s]
    pub lap_delta_to_optimal_lap_dd: f32,
    /// Delta time for optimal lap is valid
    pub lap_delta_to_optimal_lap_ok: bool,
    /// Delta time for session best lap [s]
    pub lap_delta_to_session_best_lap: f32,
    /// Rate of change of delta time for session best lap [s/s]
    pub lap_delta_to_session_best_lap_dd: f32,
    /// Delta time for session best lap is valid
    pub lap_delta_to_session_best_lap_ok: bool,
    /// Delta time for session last lap [s]
    pub lap_delta_to_session_lastl_lap: f32,
    /// Rate of change of delta time for session last lap [s/s]
    pub lap_delta_to_session_lastl_lap_dd: f32,
    /// Delta time for session last lap is valid
    pub lap_delta_to_session_lastl_lap_ok: bool,
    /// Delta time for session optimal lap [s]
    pub lap_delta_to_session_optimal_lap: f32,
    /// Rate of change of delta time for session optimal lap [s/s]
    pub lap_delta_to_session_optimal_lap_dd: f32,
    /// Delta time for session optimal lap is valid
    pub lap_delta_to_session_optimal_lap_ok: bool,
    /// Meters traveled from S/F this lap [m]
    pub lap_dist: f32,
    /// Percentage distance around lap [%]
    pub lap_dist_pct: f32,
    /// Player num consecutive clean laps completed for N average
    pub lap_las_n_lap_seq: i32,
    /// Players last lap time [s]
    pub lap_last_lap_time: f32,
    /// Player last N average lap time [s]
    pub lap_last_n_lap_time: f32,
    /// Lateral acceleration (including gravity) [m/s^2]
    pub lat_accel: f32,
    /// Lateral acceleration (including gravity) at 360 Hz [m/s^2]
    pub lat_accel_st: Vec<f32>,
    /// How many left tire sets are remaining  255 is unlimited
    pub left_tire_sets_available: i32,
    /// How many left tire sets used so far
    pub left_tire_sets_used: i32,
    /// True if the car_num texture will be loaded
    pub load_num_textures: bool,
    /// Longitudinal acceleration (including gravity) [m/s^2]
    pub long_accel: f32,
    /// Longitudinal acceleration (including gravity) at 360 Hz [m/s^2]
    pub long_accel_st: Vec<f32>,
    /// Engine manifold pressure [bar]
    pub manifold_press: f32,
    /// Hybrid manual boost state
    pub manual_boost: bool,
    /// Hybrid manual no boost state
    pub manual_no_boost: bool,
    /// Memory page faults per second
    pub mem_page_fault_sec: f32,
    /// Memory soft page faults per second
    pub mem_soft_page_fault_sec: f32,
    /// Engine oil level [l]
    pub oil_level: f32,
    /// Engine oil pressure [bar]
    pub oil_press: f32,
    /// Engine oil temperature [C]
    pub oil_temp: f32,
    /// True if it is ok to reload car textures at this time
    pub ok_to_reload_textures: bool,
    /// Is the player car on pit road between the cones
    pub on_pit_road: bool,
    /// Push2Pass count of usage (or remaining in Race) on your car
    pub p2p_count: i32,
    /// Push2Pass active or not on your car
    pub p2p_status: bool,
    /// Are we pacing or not [irsdk_PaceMode]
    pub pace_mode: i32,
    /// Time left for optional repairs if repairs are active [s]
    pub pit_opt_repair_left: f32,
    /// Time left for mandatory pit repairs if repairs are active [s]
    pub pit_repair_left: f32,
    /// Bitfield of pit service checkboxes [irsdk_PitSvFlags]
    pub pit_sv_flags: i32,
    /// Pit service fuel add amount [l or kWh]
    pub pit_sv_fuel: f32,
    /// Pit service left front tire pressure [kPa]
    pub pit_sv_lfp: f32,
    /// Pit service left rear tire pressure [kPa]
    pub pit_sv_lrp: f32,
    /// Pit service right front tire pressure [kPa]
    pub pit_sv_rfp: f32,
    /// Pit service right rear tire pressure [kPa]
    pub pit_sv_rrp: f32,
    /// Pit service pending tire compound
    pub pit_sv_tire_compound: i32,
    /// Pitch orientation [rad]
    pub pitch: f32,
    /// Pitch rate [rad/s]
    pub pitch_rate: f32,
    /// Pitch rate at 360 Hz [rad/s]
    pub pitch_rate_st: Vec<f32>,
    /// True if pit stop is allowed for the current player
    pub pits_open: bool,
    /// Is the player getting pit stop service
    pub pitstop_active: bool,
    /// Player car class id
    pub player_car_class: i32,
    /// Players class position in race
    pub player_car_class_position: i32,
    /// Teams current drivers incident count for this session
    pub player_car_driver_incident_count: i32,
    /// Players dry tire set limit
    pub player_car_dry_tire_set_limit: i32,
    /// Players carIdx
    pub player_car_idx: i32,
    /// Players car is properly in their pitstall
    pub player_car_in_pit_stall: bool,
    /// Players own incident count for this session
    pub player_car_my_incident_count: i32,
    /// Players car pit service status bits [irsdk_PitSvStatus]
    pub player_car_pit_sv_status: i32,
    /// Players position in race
    pub player_car_position: i32,
    /// Players power adjust [%]
    pub player_car_power_adjust: f32,
    /// Shift light blink rpm [revs/min]
    pub player_car_sl_blink_rpm: f32,
    /// Shift light first light rpm [revs/min]
    pub player_car_sl_first_rpm: f32,
    /// Shift light last light rpm [revs/min]
    pub player_car_sl_last_rpm: f32,
    /// Shift light shift rpm [revs/min]
    pub player_car_sl_shift_rpm: f32,
    /// Players team incident count for this session
    pub player_car_team_incident_count: i32,
    /// Players car is being towed if time is greater than zero [s]
    pub player_car_tow_time: f32,
    /// Players weight penalty [kg]
    pub player_car_weight_penalty: f32,
    /// Players car number of fast repairs used
    pub player_fast_repairs_used: i32,
    /// Log incidents that the player recieved [irsdk_IncidentFlags]
    pub player_incidents: i32,
    /// Players car current tire compound
    pub player_tire_compound: i32,
    /// Players car track surface type [irsdk_TrkLoc]
    pub player_track_surface: i32,
    /// Players car track surface material type [irsdk_TrkSurf]
    pub player_track_surface_material: i32,
    /// Precipitation at start/finish line [%]
    pub precipitation: f32,
    /// Push to pass button state
    pub push_to_pass: bool,
    /// Push to talk button state
    pub push_to_talk: bool,
    /// How many right front tires are remaining  255 is unlimited
    pub rf_tires_available: i32,
    /// How many right front tires used so far
    pub rf_tires_used: i32,
    /// RF brake line pressure [bar]
    pub r_fbrake_line_press: f32,
    /// RF tire cold pressure  as set in the garage [kPa]
    pub r_fcold_pressure: f32,
    /// RF distance tire traveled since being placed on car [m]
    pub r_fodometer: f32,
    /// RF shock deflection [m]
    pub r_fshock_defl: f32,
    /// RF shock deflection at 360 Hz [m]
    pub r_fshock_defl_st: Vec<f32>,
    /// RF shock velocity [m/s]
    pub r_fshock_vel: f32,
    /// RF shock velocity at 360 Hz [m/s]
    pub r_fshock_vel_st: Vec<f32>,
    /// RF tire left carcass temperature [C]
    pub r_ftemp_cl: f32,
    /// RF tire middle carcass temperature [C]
    pub r_ftemp_cm: f32,
    /// RF tire right carcass temperature [C]
    pub r_ftemp_cr: f32,
    /// RF tire left percent tread remaining [%]
    pub r_fwear_l: f32,
    /// RF tire middle percent tread remaining [%]
    pub r_fwear_m: f32,
    /// RF tire right percent tread remaining [%]
    pub r_fwear_r: f32,
    /// Engine rpm [revs/min]
    pub rpm: f32,
    /// How many right rear tires are remaining  255 is unlimited
    pub rr_tires_available: i32,
    /// How many right rear tires used so far
    pub rr_tires_used: i32,
    /// RR brake line pressure [bar]
    pub r_rbrake_line_press: f32,
    /// RR tire cold pressure  as set in the garage [kPa]
    pub r_rcold_pressure: f32,
    /// RR distance tire traveled since being placed on car [m]
    pub r_rodometer: f32,
    /// RR shock deflection [m]
    pub r_rshock_defl: f32,
    /// RR shock deflection at 360 Hz [m]
    pub r_rshock_defl_st: Vec<f32>,
    /// RR shock velocity [m/s]
    pub r_rshock_vel: f32,
    /// RR shock velocity at 360 Hz [m/s]
    pub r_rshock_vel_st: Vec<f32>,
    /// RR tire left carcass temperature [C]
    pub r_rtemp_cl: f32,
    /// RR tire middle carcass temperature [C]
    pub r_rtemp_cm: f32,
    /// RR tire right carcass temperature [C]
    pub r_rtemp_cr: f32,
    /// RR tire left percent tread remaining [%]
    pub r_rwear_l: f32,
    /// RR tire middle percent tread remaining [%]
    pub r_rwear_m: f32,
    /// RR tire right percent tread remaining [%]
    pub r_rwear_r: f32,
    /// Laps completed in race
    pub race_laps: i32,
    /// The car index of the current person speaking on the radio
    pub radio_transmit_car_idx: i32,
    /// The frequency index of the current person speaking on the radio
    pub radio_transmit_frequency_idx: i32,
    /// The radio index of the current person speaking on the radio
    pub radio_transmit_radio_idx: i32,
    /// How many rear tire sets are remaining  255 is unlimited
    pub rear_tire_sets_available: i32,
    /// How many rear tire sets used so far
    pub rear_tire_sets_used: i32,
    /// Relative Humidity at start/finish line [%]
    pub relative_humidity: f32,
    /// Integer replay frame number (60 per second)
    pub replay_frame_num: i32,
    /// Integer replay frame number from end of tape
    pub replay_frame_num_end: i32,
    /// 0=not slow motion  1=replay is in slow motion
    pub replay_play_slow_motion: bool,
    /// Replay playback speed
    pub replay_play_speed: i32,
    /// Replay session number
    pub replay_session_num: i32,
    /// Seconds since replay session start [s]
    pub replay_session_time: f64,
    /// How many right tire sets are remaining  255 is unlimited
    pub right_tire_sets_available: i32,
    /// How many right tire sets used so far
    pub right_tire_sets_used: i32,
    /// Roll orientation [rad]
    pub roll: f32,
    /// Roll rate [rad/s]
    pub roll_rate: f32,
    /// Roll rate at 360 Hz [rad/s]
    pub roll_rate_st: Vec<f32>,
    /// Session flags [irsdk_Flags]
    pub session_flags: i32,
    /// Joker laps remaining to be taken
    pub session_joker_laps_remain: i32,
    /// Old laps left till session ends use SessionLapsRemainEx
    pub session_laps_remain: i32,
    /// New improved laps left till session ends
    pub session_laps_remain_ex: i32,
    /// Total number of laps in session
    pub session_laps_total: i32,
    /// Session number
    pub session_num: i32,
    /// Player is currently completing a joker lap
    pub session_on_joker_lap: bool,
    /// Session state [irsdk_SessionState]
    pub session_state: i32,
    /// Current update number
    pub session_tick: i32,
    /// Seconds since session start [s]
    pub session_time: f64,
    /// Time of day in seconds [s]
    pub session_time_of_day: f32,
    /// Seconds left till session ends [s]
    pub session_time_remain: f64,
    /// Total number of seconds in session [s]
    pub session_time_total: f64,
    /// Session ID
    pub session_unique_id: i32,
    /// RPM of shifter grinding noise [RPM]
    pub shift_grind_rpm: f32,
    /// DEPRECATED use DriverCarSLBlinkRPM instead [%]
    pub shift_indicator_pct: f32,
    /// Friction torque applied to gears when shifting or grinding [%]
    pub shift_power_pct: f32,
    /// Log inputs from the players shifter control
    pub shifter: i32,
    /// Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)
    pub skies: i32,
    /// Sun angle above horizon in radians [rad]
    pub solar_altitude: f32,
    /// Sun angle clockwise from north in radians [rad]
    pub solar_azimuth: f32,
    /// GPS vehicle speed [m/s]
    pub speed: f32,
    /// Force feedback is enabled
    pub steering_ffb_enabled: bool,
    /// Steering wheel angle [rad]
    pub steering_wheel_angle: f32,
    /// Steering wheel max angle [rad]
    pub steering_wheel_angle_max: f32,
    /// Force feedback limiter strength limits impacts and oscillation [%]
    pub steering_wheel_limiter: f32,
    /// Value of strength or max force slider in Nm for FFB [N*m]
    pub steering_wheel_max_force_nm: f32,
    /// Force feedback % max damping [%]
    pub steering_wheel_pct_damper: f32,
    /// Force feedback % max intensity [%]
    pub steering_wheel_pct_intensity: f32,
    /// Force feedback % max smoothing [%]
    pub steering_wheel_pct_smoothing: f32,
    /// Force feedback % max torque on steering shaft unsigned [%]
    pub steering_wheel_pct_torque: f32,
    /// Force feedback % max torque on steering shaft signed [%]
    pub steering_wheel_pct_torque_sign: f32,
    /// Force feedback % max torque on steering shaft signed stops [%]
    pub steering_wheel_pct_torque_sign_stops: f32,
    /// Peak torque mapping to direct input units for FFB [N*m]
    pub steering_wheel_peak_force_nm: f32,
    /// Output torque on steering shaft [N*m]
    pub steering_wheel_torque: f32,
    /// Output torque on steering shaft at 360 Hz [N*m]
    pub steering_wheel_torque_st: Vec<f32>,
    /// True if steering wheel force is using linear mode
    pub steering_wheel_use_linear: bool,
    /// 0=off throttle to 1=full throttle [%]
    pub throttle: f32,
    /// Raw throttle input 0=off throttle to 1=full throttle [%]
    pub throttle_raw: f32,
    /// Players LF Tire Sound rumblestrip pitch [Hz]
    pub tire_lf_rumble_pitch: f32,
    /// Players LR Tire Sound rumblestrip pitch [Hz]
    pub tire_lr_rumble_pitch: f32,
    /// Players RF Tire Sound rumblestrip pitch [Hz]
    pub tire_rf_rumble_pitch: f32,
    /// Players RR Tire Sound rumblestrip pitch [Hz]
    pub tire_rr_rumble_pitch: f32,
    /// How many tire sets are remaining  255 is unlimited
    pub tire_sets_available: i32,
    /// How many tire sets used so far
    pub tire_sets_used: i32,
    /// Deprecated  set to TrackTempCrew [C]
    pub track_temp: f32,
    /// Temperature of track measured by crew around track [C]
    pub track_temp_crew: f32,
    /// How wet is the average track surface [irsdk_TrackWetness]
    pub track_wetness: i32,
    /// X velocity [m/s]
    pub velocity_x: f32,
    /// X velocity [m/s at 360 Hz]
    pub velocity_x_st: Vec<f32>,
    /// Y velocity [m/s]
    pub velocity_y: f32,
    /// Y velocity [m/s at 360 Hz]
    pub velocity_y_st: Vec<f32>,
    /// Z velocity [m/s]
    pub velocity_z: f32,
    /// Z velocity [m/s at 360 Hz]
    pub velocity_z_st: Vec<f32>,
    /// Vertical acceleration (including gravity) [m/s^2]
    pub vert_accel: f32,
    /// Vertical acceleration (including gravity) at 360 Hz [m/s^2]
    pub vert_accel_st: Vec<f32>,
    /// True if video currently being captured
    pub vid_cap_active: bool,
    /// True if video capture system is enabled
    pub vid_cap_enabled: bool,
    /// Engine voltage [V]
    pub voltage: f32,
    /// Engine coolant level [l]
    pub water_level: f32,
    /// Engine coolant temp [C]
    pub water_temp: f32,
    /// The steward says rain tires can be used
    pub weather_declared_wet: bool,
    /// Wind direction at start/finish line [rad]
    pub wind_dir: f32,
    /// Wind velocity at start/finish line [m/s]
    pub wind_vel: f32,
    /// Yaw orientation [rad]
    pub yaw: f32,
    /// Yaw orientation relative to north [rad]
    pub yaw_north: f32,
    /// Yaw rate [rad/s]
    pub yaw_rate: f32,
    /// Yaw rate at 360 Hz [rad/s]
    pub yaw_rate_st: Vec<f32>,
    /// Track if pit speed limiter system is enabled
    pub dc_pit_speed_limiter_toggle: bool,
    /// In car trigger car starter
    pub dc_starter: bool,
    /// In car turn wipers on or off
    pub dc_toggle_windshield_wipers: bool,
    /// In car momentarily turn on wipers
    pub dc_trigger_windshield_wipers: bool,
    /// Pitstop fast repair set
    pub dp_fast_repair: f32,
    /// Pitstop fuel add amount [kg]
    pub dp_fuel_add_kg: f32,
    /// Pitstop auto fill fuel next stop flag
    pub dp_fuel_auto_fill_active: f32,
    /// Pitstop auto fill fuel system enabled
    pub dp_fuel_auto_fill_enabled: f32,
    /// Pitstop fuel fill flag
    pub dp_fuel_fill: f32,
    /// Pitstop lf tire change request
    pub dp_lf_tire_change: f32,
    /// Pitstop lf tire cold pressure adjustment [Pa]
    pub dp_lf_tire_cold_press: f32,
    /// Pitstop lr tire change request
    pub dp_lr_tire_change: f32,
    /// Pitstop lr tire cold pressure adjustment [Pa]
    pub dp_lr_tire_cold_press: f32,
    /// Pitstop rf tire change request
    pub dp_rf_tire_change: f32,
    /// Pitstop rf cold tire pressure adjustment [Pa]
    pub dp_rf_tire_cold_press: f32,
    /// Pitstop rr tire change request
    pub dp_rr_tire_change: f32,
    /// Pitstop rr cold tire pressure adjustment [Pa]
    pub dp_rr_tire_cold_press: f32,
    /// Pitstop windshield tearoff
    pub dp_windshield_tearoff: f32,
}

impl IracingFrame {
    pub(crate) fn from_vars(vars: &HashMap<String, crate::types::TelemetryValue>) -> Self {
        Self {
            air_density: match vars.get("AirDensity") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            air_pressure: match vars.get("AirPressure") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            air_temp: match vars.get("AirTemp") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            brake: match vars.get("Brake") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            brake_ab_sactive: match vars.get("BrakeABSactive") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            brake_raw: match vars.get("BrakeRaw") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            cam_camera_number: match vars.get("CamCameraNumber") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            cam_camera_state: match vars.get("CamCameraState") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            cam_car_idx: match vars.get("CamCarIdx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            cam_group_number: match vars.get("CamGroupNumber") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            car_dist_ahead: match vars.get("CarDistAhead") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            car_dist_behind: match vars.get("CarDistBehind") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            car_idx_best_lap_num: match vars.get("CarIdxBestLapNum") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_best_lap_time: match vars.get("CarIdxBestLapTime") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_class: match vars.get("CarIdxClass") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_class_position: match vars.get("CarIdxClassPosition") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_est_time: match vars.get("CarIdxEstTime") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_f2time: match vars.get("CarIdxF2Time") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_fast_repairs_used: match vars.get("CarIdxFastRepairsUsed") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_gear: match vars.get("CarIdxGear") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_lap: match vars.get("CarIdxLap") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_lap_completed: match vars.get("CarIdxLapCompleted") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_lap_dist_pct: match vars.get("CarIdxLapDistPct") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_last_lap_time: match vars.get("CarIdxLastLapTime") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_on_pit_road: match vars.get("CarIdxOnPitRoad") {
                Some(crate::types::TelemetryValue::BoolArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_p2p_count: match vars.get("CarIdxP2P_Count") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_p2p_status: match vars.get("CarIdxP2P_Status") {
                Some(crate::types::TelemetryValue::BoolArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_pace_flags: match vars.get("CarIdxPaceFlags") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_pace_line: match vars.get("CarIdxPaceLine") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_pace_row: match vars.get("CarIdxPaceRow") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_position: match vars.get("CarIdxPosition") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_qual_tire_compound: match vars.get("CarIdxQualTireCompound") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_qual_tire_compound_locked: match vars.get("CarIdxQualTireCompoundLocked") {
                Some(crate::types::TelemetryValue::BoolArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_rpm: match vars.get("CarIdxRPM") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_session_flags: match vars.get("CarIdxSessionFlags") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_steer: match vars.get("CarIdxSteer") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_tire_compound: match vars.get("CarIdxTireCompound") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_track_surface: match vars.get("CarIdxTrackSurface") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_idx_track_surface_material: match vars.get("CarIdxTrackSurfaceMaterial") {
                Some(crate::types::TelemetryValue::IntArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            car_left_right: match vars.get("CarLeftRight") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            chan_avg_latency: match vars.get("ChanAvgLatency") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            chan_clock_skew: match vars.get("ChanClockSkew") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            chan_latency: match vars.get("ChanLatency") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            chan_partner_quality: match vars.get("ChanPartnerQuality") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            chan_quality: match vars.get("ChanQuality") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            clutch: match vars.get("Clutch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            clutch_raw: match vars.get("ClutchRaw") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            cpu_usage_bg: match vars.get("CpuUsageBG") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            cpu_usage_fg: match vars.get("CpuUsageFG") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dc_drivers_so_far: match vars.get("DCDriversSoFar") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            dc_lap_status: match vars.get("DCLapStatus") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            display_units: match vars.get("DisplayUnits") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            driver_marker: match vars.get("DriverMarker") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            engine0_rpm: match vars.get("Engine0_RPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            engine_warnings: match vars.get("EngineWarnings") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            enter_exit_reset: match vars.get("EnterExitReset") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            fast_repair_available: match vars.get("FastRepairAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            fast_repair_used: match vars.get("FastRepairUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            fog_level: match vars.get("FogLevel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            frame_rate: match vars.get("FrameRate") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            front_tire_sets_available: match vars.get("FrontTireSetsAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            front_tire_sets_used: match vars.get("FrontTireSetsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            fuel_level: match vars.get("FuelLevel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            fuel_level_pct: match vars.get("FuelLevelPct") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            fuel_press: match vars.get("FuelPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            fuel_use_per_hour: match vars.get("FuelUsePerHour") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            gear: match vars.get("Gear") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            gpu_usage: match vars.get("GpuUsage") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            handbrake_raw: match vars.get("HandbrakeRaw") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            is_disk_logging_active: match vars.get("IsDiskLoggingActive") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_disk_logging_enabled: match vars.get("IsDiskLoggingEnabled") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_garage_visible: match vars.get("IsGarageVisible") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_in_garage: match vars.get("IsInGarage") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_on_track: match vars.get("IsOnTrack") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_on_track_car: match vars.get("IsOnTrackCar") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            is_replay_playing: match vars.get("IsReplayPlaying") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lf_tires_available: match vars.get("LFTiresAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lf_tires_used: match vars.get("LFTiresUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            l_fbrake_line_press: match vars.get("LFbrakeLinePress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fcold_pressure: match vars.get("LFcoldPressure") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fodometer: match vars.get("LFodometer") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fshock_defl: match vars.get("LFshockDefl") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fshock_defl_st: match vars.get("LFshockDefl_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            l_fshock_vel: match vars.get("LFshockVel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fshock_vel_st: match vars.get("LFshockVel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            l_ftemp_cl: match vars.get("LFtempCL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_ftemp_cm: match vars.get("LFtempCM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_ftemp_cr: match vars.get("LFtempCR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fwear_l: match vars.get("LFwearL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fwear_m: match vars.get("LFwearM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_fwear_r: match vars.get("LFwearR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lr_tires_available: match vars.get("LRTiresAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lr_tires_used: match vars.get("LRTiresUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            l_rbrake_line_press: match vars.get("LRbrakeLinePress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rcold_pressure: match vars.get("LRcoldPressure") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rodometer: match vars.get("LRodometer") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rshock_defl: match vars.get("LRshockDefl") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rshock_defl_st: match vars.get("LRshockDefl_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            l_rshock_vel: match vars.get("LRshockVel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rshock_vel_st: match vars.get("LRshockVel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            l_rtemp_cl: match vars.get("LRtempCL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rtemp_cm: match vars.get("LRtempCM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rtemp_cr: match vars.get("LRtempCR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rwear_l: match vars.get("LRwearL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rwear_m: match vars.get("LRwearM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            l_rwear_r: match vars.get("LRwearR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap: match vars.get("Lap") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lap_best_lap: match vars.get("LapBestLap") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lap_best_lap_time: match vars.get("LapBestLapTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_best_n_lap_lap: match vars.get("LapBestNLapLap") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lap_best_n_lap_time: match vars.get("LapBestNLapTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_completed: match vars.get("LapCompleted") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lap_current_lap_time: match vars.get("LapCurrentLapTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_best_lap: match vars.get("LapDeltaToBestLap") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_best_lap_dd: match vars.get("LapDeltaToBestLap_DD") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_best_lap_ok: match vars.get("LapDeltaToBestLap_OK") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lap_delta_to_optimal_lap: match vars.get("LapDeltaToOptimalLap") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_optimal_lap_dd: match vars.get("LapDeltaToOptimalLap_DD") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_optimal_lap_ok: match vars.get("LapDeltaToOptimalLap_OK") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lap_delta_to_session_best_lap: match vars.get("LapDeltaToSessionBestLap") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_best_lap_dd: match vars.get("LapDeltaToSessionBestLap_DD") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_best_lap_ok: match vars.get("LapDeltaToSessionBestLap_OK") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lap_delta_to_session_lastl_lap: match vars.get("LapDeltaToSessionLastlLap") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_lastl_lap_dd: match vars.get("LapDeltaToSessionLastlLap_DD") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_lastl_lap_ok: match vars.get("LapDeltaToSessionLastlLap_OK") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lap_delta_to_session_optimal_lap: match vars.get("LapDeltaToSessionOptimalLap") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_optimal_lap_dd: match vars.get("LapDeltaToSessionOptimalLap_DD") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_delta_to_session_optimal_lap_ok: match vars.get("LapDeltaToSessionOptimalLap_OK") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            lap_dist: match vars.get("LapDist") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_dist_pct: match vars.get("LapDistPct") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_las_n_lap_seq: match vars.get("LapLasNLapSeq") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            lap_last_lap_time: match vars.get("LapLastLapTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lap_last_n_lap_time: match vars.get("LapLastNLapTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lat_accel: match vars.get("LatAccel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            lat_accel_st: match vars.get("LatAccel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            left_tire_sets_available: match vars.get("LeftTireSetsAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            left_tire_sets_used: match vars.get("LeftTireSetsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            load_num_textures: match vars.get("LoadNumTextures") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            long_accel: match vars.get("LongAccel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            long_accel_st: match vars.get("LongAccel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            manifold_press: match vars.get("ManifoldPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            manual_boost: match vars.get("ManualBoost") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            manual_no_boost: match vars.get("ManualNoBoost") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            mem_page_fault_sec: match vars.get("MemPageFaultSec") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            mem_soft_page_fault_sec: match vars.get("MemSoftPageFaultSec") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            oil_level: match vars.get("OilLevel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            oil_press: match vars.get("OilPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            oil_temp: match vars.get("OilTemp") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            ok_to_reload_textures: match vars.get("OkToReloadTextures") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            on_pit_road: match vars.get("OnPitRoad") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            p2p_count: match vars.get("P2P_Count") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            p2p_status: match vars.get("P2P_Status") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            pace_mode: match vars.get("PaceMode") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            pit_opt_repair_left: match vars.get("PitOptRepairLeft") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_repair_left: match vars.get("PitRepairLeft") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_flags: match vars.get("PitSvFlags") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            pit_sv_fuel: match vars.get("PitSvFuel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_lfp: match vars.get("PitSvLFP") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_lrp: match vars.get("PitSvLRP") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_rfp: match vars.get("PitSvRFP") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_rrp: match vars.get("PitSvRRP") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pit_sv_tire_compound: match vars.get("PitSvTireCompound") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            pitch: match vars.get("Pitch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pitch_rate: match vars.get("PitchRate") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            pitch_rate_st: match vars.get("PitchRate_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            pits_open: match vars.get("PitsOpen") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            pitstop_active: match vars.get("PitstopActive") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            player_car_class: match vars.get("PlayerCarClass") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_class_position: match vars.get("PlayerCarClassPosition") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_driver_incident_count: match vars.get("PlayerCarDriverIncidentCount") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_dry_tire_set_limit: match vars.get("PlayerCarDryTireSetLimit") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_idx: match vars.get("PlayerCarIdx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_in_pit_stall: match vars.get("PlayerCarInPitStall") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            player_car_my_incident_count: match vars.get("PlayerCarMyIncidentCount") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_pit_sv_status: match vars.get("PlayerCarPitSvStatus") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_position: match vars.get("PlayerCarPosition") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_power_adjust: match vars.get("PlayerCarPowerAdjust") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_sl_blink_rpm: match vars.get("PlayerCarSLBlinkRPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_sl_first_rpm: match vars.get("PlayerCarSLFirstRPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_sl_last_rpm: match vars.get("PlayerCarSLLastRPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_sl_shift_rpm: match vars.get("PlayerCarSLShiftRPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_team_incident_count: match vars.get("PlayerCarTeamIncidentCount") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_car_tow_time: match vars.get("PlayerCarTowTime") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_car_weight_penalty: match vars.get("PlayerCarWeightPenalty") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            player_fast_repairs_used: match vars.get("PlayerFastRepairsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_incidents: match vars.get("PlayerIncidents") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_tire_compound: match vars.get("PlayerTireCompound") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_track_surface: match vars.get("PlayerTrackSurface") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            player_track_surface_material: match vars.get("PlayerTrackSurfaceMaterial") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            precipitation: match vars.get("Precipitation") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            push_to_pass: match vars.get("PushToPass") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            push_to_talk: match vars.get("PushToTalk") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            rf_tires_available: match vars.get("RFTiresAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            rf_tires_used: match vars.get("RFTiresUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            r_fbrake_line_press: match vars.get("RFbrakeLinePress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fcold_pressure: match vars.get("RFcoldPressure") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fodometer: match vars.get("RFodometer") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fshock_defl: match vars.get("RFshockDefl") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fshock_defl_st: match vars.get("RFshockDefl_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            r_fshock_vel: match vars.get("RFshockVel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fshock_vel_st: match vars.get("RFshockVel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            r_ftemp_cl: match vars.get("RFtempCL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_ftemp_cm: match vars.get("RFtempCM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_ftemp_cr: match vars.get("RFtempCR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fwear_l: match vars.get("RFwearL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fwear_m: match vars.get("RFwearM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_fwear_r: match vars.get("RFwearR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            rpm: match vars.get("RPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            rr_tires_available: match vars.get("RRTiresAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            rr_tires_used: match vars.get("RRTiresUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            r_rbrake_line_press: match vars.get("RRbrakeLinePress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rcold_pressure: match vars.get("RRcoldPressure") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rodometer: match vars.get("RRodometer") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rshock_defl: match vars.get("RRshockDefl") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rshock_defl_st: match vars.get("RRshockDefl_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            r_rshock_vel: match vars.get("RRshockVel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rshock_vel_st: match vars.get("RRshockVel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            r_rtemp_cl: match vars.get("RRtempCL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rtemp_cm: match vars.get("RRtempCM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rtemp_cr: match vars.get("RRtempCR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rwear_l: match vars.get("RRwearL") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rwear_m: match vars.get("RRwearM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            r_rwear_r: match vars.get("RRwearR") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            race_laps: match vars.get("RaceLaps") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            radio_transmit_car_idx: match vars.get("RadioTransmitCarIdx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            radio_transmit_frequency_idx: match vars.get("RadioTransmitFrequencyIdx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            radio_transmit_radio_idx: match vars.get("RadioTransmitRadioIdx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            rear_tire_sets_available: match vars.get("RearTireSetsAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            rear_tire_sets_used: match vars.get("RearTireSetsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            relative_humidity: match vars.get("RelativeHumidity") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            replay_frame_num: match vars.get("ReplayFrameNum") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            replay_frame_num_end: match vars.get("ReplayFrameNumEnd") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            replay_play_slow_motion: match vars.get("ReplayPlaySlowMotion") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            replay_play_speed: match vars.get("ReplayPlaySpeed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            replay_session_num: match vars.get("ReplaySessionNum") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            replay_session_time: match vars.get("ReplaySessionTime") {
                Some(crate::types::TelemetryValue::Double(v)) => *v,
                _ => 0.0,
            },
            right_tire_sets_available: match vars.get("RightTireSetsAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            right_tire_sets_used: match vars.get("RightTireSetsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            roll: match vars.get("Roll") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            roll_rate: match vars.get("RollRate") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            roll_rate_st: match vars.get("RollRate_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            session_flags: match vars.get("SessionFlags") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_joker_laps_remain: match vars.get("SessionJokerLapsRemain") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_laps_remain: match vars.get("SessionLapsRemain") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_laps_remain_ex: match vars.get("SessionLapsRemainEx") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_laps_total: match vars.get("SessionLapsTotal") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_num: match vars.get("SessionNum") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_on_joker_lap: match vars.get("SessionOnJokerLap") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            session_state: match vars.get("SessionState") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_tick: match vars.get("SessionTick") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            session_time: match vars.get("SessionTime") {
                Some(crate::types::TelemetryValue::Double(v)) => *v,
                _ => 0.0,
            },
            session_time_of_day: match vars.get("SessionTimeOfDay") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            session_time_remain: match vars.get("SessionTimeRemain") {
                Some(crate::types::TelemetryValue::Double(v)) => *v,
                _ => 0.0,
            },
            session_time_total: match vars.get("SessionTimeTotal") {
                Some(crate::types::TelemetryValue::Double(v)) => *v,
                _ => 0.0,
            },
            session_unique_id: match vars.get("SessionUniqueID") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            shift_grind_rpm: match vars.get("ShiftGrindRPM") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            shift_indicator_pct: match vars.get("ShiftIndicatorPct") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            shift_power_pct: match vars.get("ShiftPowerPct") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            shifter: match vars.get("Shifter") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            skies: match vars.get("Skies") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            solar_altitude: match vars.get("SolarAltitude") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            solar_azimuth: match vars.get("SolarAzimuth") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            speed: match vars.get("Speed") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_ffb_enabled: match vars.get("SteeringFFBEnabled") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            steering_wheel_angle: match vars.get("SteeringWheelAngle") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_angle_max: match vars.get("SteeringWheelAngleMax") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_limiter: match vars.get("SteeringWheelLimiter") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_max_force_nm: match vars.get("SteeringWheelMaxForceNm") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_damper: match vars.get("SteeringWheelPctDamper") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_intensity: match vars.get("SteeringWheelPctIntensity") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_smoothing: match vars.get("SteeringWheelPctSmoothing") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_torque: match vars.get("SteeringWheelPctTorque") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_torque_sign: match vars.get("SteeringWheelPctTorqueSign") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_pct_torque_sign_stops: match vars.get("SteeringWheelPctTorqueSignStops")
            {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_peak_force_nm: match vars.get("SteeringWheelPeakForceNm") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_torque: match vars.get("SteeringWheelTorque") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            steering_wheel_torque_st: match vars.get("SteeringWheelTorque_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            steering_wheel_use_linear: match vars.get("SteeringWheelUseLinear") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            throttle: match vars.get("Throttle") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            throttle_raw: match vars.get("ThrottleRaw") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            tire_lf_rumble_pitch: match vars.get("TireLF_RumblePitch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            tire_lr_rumble_pitch: match vars.get("TireLR_RumblePitch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            tire_rf_rumble_pitch: match vars.get("TireRF_RumblePitch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            tire_rr_rumble_pitch: match vars.get("TireRR_RumblePitch") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            tire_sets_available: match vars.get("TireSetsAvailable") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            tire_sets_used: match vars.get("TireSetsUsed") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            track_temp: match vars.get("TrackTemp") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            track_temp_crew: match vars.get("TrackTempCrew") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            track_wetness: match vars.get("TrackWetness") {
                Some(crate::types::TelemetryValue::Int(v)) => *v,
                _ => 0,
            },
            velocity_x: match vars.get("VelocityX") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            velocity_x_st: match vars.get("VelocityX_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            velocity_y: match vars.get("VelocityY") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            velocity_y_st: match vars.get("VelocityY_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            velocity_z: match vars.get("VelocityZ") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            velocity_z_st: match vars.get("VelocityZ_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            vert_accel: match vars.get("VertAccel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            vert_accel_st: match vars.get("VertAccel_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            vid_cap_active: match vars.get("VidCapActive") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            vid_cap_enabled: match vars.get("VidCapEnabled") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            voltage: match vars.get("Voltage") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            water_level: match vars.get("WaterLevel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            water_temp: match vars.get("WaterTemp") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            weather_declared_wet: match vars.get("WeatherDeclaredWet") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            wind_dir: match vars.get("WindDir") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            wind_vel: match vars.get("WindVel") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            yaw: match vars.get("Yaw") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            yaw_north: match vars.get("YawNorth") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            yaw_rate: match vars.get("YawRate") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            yaw_rate_st: match vars.get("YawRate_ST") {
                Some(crate::types::TelemetryValue::FloatArray(v)) => v.clone(),
                _ => Vec::new(),
            },
            dc_pit_speed_limiter_toggle: match vars.get("dcPitSpeedLimiterToggle") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            dc_starter: match vars.get("dcStarter") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            dc_toggle_windshield_wipers: match vars.get("dcToggleWindshieldWipers") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            dc_trigger_windshield_wipers: match vars.get("dcTriggerWindshieldWipers") {
                Some(crate::types::TelemetryValue::Bool(v)) => *v,
                _ => false,
            },
            dp_fast_repair: match vars.get("dpFastRepair") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_fuel_add_kg: match vars.get("dpFuelAddKg") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_fuel_auto_fill_active: match vars.get("dpFuelAutoFillActive") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_fuel_auto_fill_enabled: match vars.get("dpFuelAutoFillEnabled") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_fuel_fill: match vars.get("dpFuelFill") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_lf_tire_change: match vars.get("dpLFTireChange") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_lf_tire_cold_press: match vars.get("dpLFTireColdPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_lr_tire_change: match vars.get("dpLRTireChange") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_lr_tire_cold_press: match vars.get("dpLRTireColdPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_rf_tire_change: match vars.get("dpRFTireChange") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_rf_tire_cold_press: match vars.get("dpRFTireColdPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_rr_tire_change: match vars.get("dpRRTireChange") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_rr_tire_cold_press: match vars.get("dpRRTireColdPress") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
            dp_windshield_tearoff: match vars.get("dpWindshieldTearoff") {
                Some(crate::types::TelemetryValue::Float(v)) => *v,
                _ => 0.0,
            },
        }
    }

    /// Build a frame by reading each variable directly from the connection.
    /// Single-pass: no intermediate HashMap allocation.
    pub(crate) fn from_connection(conn: &crate::iracing::connection::IRsdkConnection) -> Self {
        Self::from_vars(&conn.read_all_variables())
    }
}
